### ISSUE TITLE
ascii.pyについて

### ISSUE THREAD

**Issue by Bigdrea6** [doiuec/file_less#3]
- i、m、numboxの用途が分からなかった
- charの中身がhex、binで表されている場合の考慮はしたほうがよさそう
- numboxの変数名変更とnumbox = []はforの中の方がよさそう?(forの中でのみ使用するならそうした方がよさそう)
- コメントの"T/n s/n i/n !" は "T\n s\n i\n !"かなと思いました

**Comment by side-realms** [comment]
・i, m, numbox はデバッグの名残でした
・コメントは修正しました
・char[~~] じゃなくて [char]~~ + だったので修正しました
