### ISSUE TITLE
replace.pyについて

### ISSUE THREAD

**Issue by Bigdrea6** [doiuec/file_less#4]
- beforeとkeyで分けているけれど、一緒でいいのではと思った
- replaceについて、re.IGNORECASEを適用したほうが良いと思った
- before内の.+?は.+で大丈夫じゃないかなと思いましたが、理由ありそうだから無理に修正する必要は無いと思います

**Comment by side-realms** [comment]
・before と key で分けているのは自分が分かりやすいからです，いつか冗長なので書きかえ
・re.IGNORECASE を追加しました
・.+? は非貪マッチしてほしいからです．これをしないと 'This is' .replace(' にマッチして都合が悪い
