### ISSUE TITLE
base64_cipher.py

### ISSUE THREAD

**Issue by side-realms** [doiuec/file_less#5]
・r".+base64.+", だと [System.Convert]より前に平文があるとその範囲も検知してしまうので[System.Convert]をハードコードしてもいいと思いました
e.g. data= 'hello [System.Convert]::FromBase64String("ZXhhbXBsZQ==")'

**Comment by Bigdrea6** [comment]
[System.Convert]と)で囲むようにしました

**Comment by Bigdrea6** [comment]
マージしました
